document.write( '<!doctype html>\n' );
document.write( '<html>\n' );
document.write( '  <head>\n' );
document.write( '    <meta charset=“UTF-8”>\n' );
document.write( '    <link rel=\"stylesheet\" href=\"style.css\">\n' );
document.write( '\n' );
document.write( '    <title>Antifa Playlist</title>\n' );
document.write( '  </head>\n' );
document.write( '  <body>\n' );
document.write( '    <table class=\"table table-bordered table-hover table-condensed\">\n' );
document.write( '        <div class=\"table-wrapper\" tabindex=\"0\">\n' );
document.write( '            <thead>\n' );
document.write( '                <tr>\n' );
document.write( '                    <th title=\"Field #1\">title</th>\n' );
document.write( '                    <th title=\"Field #2\">artist</th>\n' );
document.write( '                    <th title=\"Field #3\">year</th>\n' );
document.write( '                    <th title=\"Field #4\">place</th>\n' );
document.write( '                    <th title=\"Field #5\">file / link</th>\n' );
document.write( '                    <th title=\"Field #6\">antifacist</th>\n' );
document.write( '                    <th title=\"Field #7\">facist</th>\n' );
document.write( '                    <th title=\"Field #8\">ambiguous</th>\n' );
document.write( '                    <th title=\"Field #9\">anarchist</th>\n' );
document.write( '                </tr>\n' );
document.write( '            </thead>\n' );
document.write( '            <tbody>\n' );
document.write( '                <tr>\n' );
document.write( '                    <td>A las Barricadas</td>\n' );
document.write( '                    <td>Józef Pławiński</td>\n' );
document.write( '                    <td>1879</td>\n' );
document.write( '                    <td>spain</td>\n' );
document.write( '                    <td><a href=\"https://www.youtube.com/watch?v=o_sardhLRwk\" style=\"display:block; \">🎶\n' );
document.write( '    \n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>TRUE</td>\n' );
document.write( '    </tr>\n' );
document.write( '    <tr>\n' );
document.write( '    <td>En la plaza de mi pueblo</td>\n' );
document.write( '    <td>Federico García Lorca</td>\n' );
document.write( '    <td>1936</td>\n' );
document.write( '    <td>spain</td>\n' );
document.write( '    <td><a href=\"https://www.youtube.com/watch?v=UnejUWRam-0\" style=\"display:block; \">🎶\n' );
document.write( '    \n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>TRUE</td>\n' );
document.write( '    </tr>\n' );
document.write( '    <tr>\n' );
document.write( '    <td>Here's to You</td>\n' );
document.write( '    <td>Joan Baez & Ennio Morricone</td>\n' );
document.write( '    <td>1971</td>\n' );
document.write( '    <td>US</td>\n' );
document.write( '    <td><a href=\"https://www.youtube.com/watch?v=7oday_Fc-Gc\" style=\"display:block; \">🎶\n' );
document.write( '    \n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>TRUE</td>\n' );
document.write( '    </tr>\n' );
document.write( '    <tr>\n' );
document.write( '    <td>Hijos del Pueblo </td>\n' );
document.write( '    <td>-----</td>\n' );
document.write( '    <td align=\"right\">1885</td>\n' );
document.write( '    <td>spanish</td>\n' );
document.write( '    <td><a href=\"https://www.youtube.com/watch?v=_Fbz2A2u1hs\" style=\"display:block; \">🎶\n' );
document.write( '    \n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>TRUE</td>\n' );
document.write( '    </tr>\n' );
document.write( '    <tr>\n' );
document.write( '    <td>Himno Zapatista</td>\n' );
document.write( '    <td>-----</td>\n' );
document.write( '    <td align=\"right\">1994</td>\n' );
document.write( '    <td>mexico</td>\n' );
document.write( '    <td><a href=\"https://www.youtube.com/watch?v=fK51dmnHve0\" style=\"display:block; \">🎶\n' );
document.write( '    \n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>TRUE</td>\n' );
document.write( '    </tr>\n' );
document.write( '    <tr>\n' );
document.write( '    <td>La marseillaise de la Commune</td>\n' );
document.write( '    <td>Claude Joseph Rouget de Lisle, 1792</td>\n' );
document.write( '    <td align=\"right\">1871</td>\n' );
document.write( '    <td>france</td>\n' );
document.write( '    <td><a href=\"https://www.youtube.com/watch?v=fdk0kx_CaJ4\" style=\"display:block; \">🎶\n' );
document.write( '    \n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>TRUE</td>\n' );
document.write( '    </tr>\n' );
document.write( '    <tr>\n' );
document.write( '    <td>Le drapeau rouge</td>\n' );
document.write( '    <td>Paul Brousse</td>\n' );
document.write( '    <td align=\"right\">1877</td>\n' );
document.write( '    <td>france</td>\n' );
document.write( '    <td><a href=\"https://www.youtube.com/watch?v=RPfwKyJmvfE\" style=\"display:block; \">🎶\n' );
document.write( '    \n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>TRUE</td>\n' );
document.write( '    </tr>\n' );
document.write( '    <tr>\n' );
document.write( '    <td>Viva la FAI</td>\n' );
document.write( '    <td>-----</td>\n' );
document.write( '    <td align=\"right\">1930</td>\n' );
document.write( '    <td>spain</td>\n' );
document.write( '    <td><a href=\"https://www.youtube.com/watch?v=O3_Ym9l9m1wE\" style=\"display:block; \">🎶\n' );
document.write( '    \n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>TRUE</td>\n' );
document.write( '    </tr>\n' );
document.write( '    <tr>\n' );
document.write( '    <td>Bella ciao</td>\n' );
document.write( '    <td> </td>\n' );
document.write( '    <td align=\"right\">1900</td>\n' );
document.write( '    <td>italian</td>\n' );
document.write( '    <td><a href=\"https://www.youtube.com/watch?v=0aUav1lx3rAr\" style=\"display:block; \">🎶\n' );
document.write( '    \n' );
document.write( '    <td>TRUE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    </tr>\n' );
document.write( '    <tr>\n' );
document.write( '    <td>Bonzo goes to Bitburg</td>\n' );
document.write( '    <td>Ramones</td>\n' );
document.write( '    <td align=\"right\">1985</td>\n' );
document.write( '    <td>UK</td>\n' );
document.write( '    <td><a href=\"https://www.youtube.com/watch?v=P-L_5HedJbwr\" style=\"display:block; \">🎶\n' );
document.write( '    \n' );
document.write( '    <td>TRUE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    </tr>\n' );
document.write( '    <tr>\n' );
document.write( '    <td>California über alles</td>\n' );
document.write( '    <td>Dead Kennedys</td>\n' );
document.write( '    <td align=\"right\">1979</td>\n' );
document.write( '    <td>US</td>\n' );
document.write( '    <td><a href=\"https://www.youtube.com/watch?v=jrWflCJPM4w\" style=\"display:block; \">🎶\n' );
document.write( '    \n' );
document.write( '    <td>TRUE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    </tr>\n' );
document.write( '    <tr>\n' );
document.write( '    <td>Enough is Enough</td>\n' );
document.write( '    <td>Chumbawamba</td>\n' );
document.write( '    <td align=\"right\">1993</td>\n' );
document.write( '    <td>UK</td>\n' );
document.write( '    <td><a href=\"https://www.youtube.com/watch?v=lejdEInKS-I\" style=\"display:block; \">🎶\n' );
document.write( '    \n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>TRUE</td>\n' );
document.write( '    </tr>\n' );
document.write( '    <tr>\n' );
document.write( '    <td>Fascist cops</td>\n' );
document.write( '    <td>The kids</td>\n' );
document.write( '    <td align=\"right\">1978</td>\n' );
document.write( '    <td>Belgian</td>\n' );
document.write( '    <td><a href=\"https://www.youtube.com/watch?v=Nvj6eP-UGGw\" style=\"display:block; \">🎶\n' );
document.write( '    \n' );
document.write( '    <td>TRUE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    </tr>\n' );
document.write( '    <tr>\n' );
document.write( '    <td>This land is your land</td>\n' );
document.write( '    <td>Woody Guthrie</td>\n' );
document.write( '    <td align=\"right\">1940</td>\n' );
document.write( '    <td>US</td>\n' );
document.write( '    <td><a href=\"https://www.youtube.com/watch?v=wxiMrvDbq3s\" style=\"display:block; \">🎶\n' );
document.write( '    \n' );
document.write( '    <td>TRUE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    </tr>\n' );
document.write( '    <tr>\n' );
document.write( '    <td>Hitler has only got one ball</td>\n' );
document.write( '    <td>F. J. Rickettes</td>\n' );
document.write( '    <td align=\"right\">1939</td>\n' );
document.write( '    <td>UK</td>\n' );
document.write( '    <td><a href=\"https://www.youtube.com/watch?v=gqZg36JBBr8\" style=\"display:block; \">🎶\n' );
document.write( '    \n' );
document.write( '    <td>TRUE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    </tr>\n' );
document.write( '    <tr>\n' );
document.write( '    <td>Nazi punks fuck off</td>\n' );
document.write( '    <td>Dead Kennedys</td>\n' );
document.write( '    <td align=\"right\">1981</td>\n' );
document.write( '    <td>US</td>\n' );
document.write( '    <td><a href=\"https://www.youtube.com/watch?v=vKnEELxcLbM\" style=\"display:block; \">🎶\n' );
document.write( '    \n' );
document.write( '    <td>TRUE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    </tr>\n' );
document.write( '    <tr>\n' );
document.write( '    <td>The partisan</td>\n' );
document.write( '    <td>Anna Marly </td>\n' );
document.write( '    <td align=\"right\">1943</td>\n' );
document.write( '    <td>france</td>\n' );
document.write( '    <td><a href=\"https://www.youtube.com/watch?v=9RYy_8u4blk\" style=\"display:block; \">🎶\n' );
document.write( '    \n' );
document.write( '    <td>TRUE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    </tr>\n' );
document.write( '    <tr>\n' );
document.write( '    <td>(We Don't Need This) Fascist Groove Thang</td>\n' );
document.write( '    <td>Heaven 17</td>\n' );
document.write( '    <td align=\"right\">1981</td>\n' );
document.write( '    <td>UK</td>\n' );
document.write( '    <td><a href=\"https://www.youtube.com/watch?v=lV5dbcOmw6I\" style=\"display:block; \">🎶\n' );
document.write( '    \n' );
document.write( '    <td>TRUE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    </tr>\n' );
document.write( '    <tr>\n' );
document.write( '    <td>Triumph of the Swill</td>\n' );
document.write( '    <td>Dead Kennedys</td>\n' );
document.write( '    <td align=\"right\">1986</td>\n' );
document.write( '    <td>US</td>\n' );
document.write( '    <td><a href=\"https://www.youtube.com/watch?v=68ekngSyuLM\" style=\"display:block; \">🎶\n' );
document.write( '    \n' );
document.write( '    <td>TRUE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    </tr>\n' );
document.write( '    <tr>\n' );
document.write( '    <td>Anarchy for Sale</td>\n' );
document.write( '    <td>Dead Kennedys</td>\n' );
document.write( '    <td align=\"right\">1986</td>\n' );
document.write( '    <td>US</td>\n' );
document.write( '    <td><a href=\"https://www.youtube.com/watch?v=q3gNgS9E6k8\" style=\"display:block; \">🎶\n' );
document.write( '    \n' );
document.write( '    <td>TRUE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    </tr>\n' );
document.write( '    <tr>\n' );
document.write( '    <td>Holiday in Cambodia</td>\n' );
document.write( '    <td>Dead Kennedys</td>\n' );
document.write( '    <td align=\"right\">1980</td>\n' );
document.write( '    <td>US</td>\n' );
document.write( '    <td><a href=\"https://www.youtube.com/watch?v=Ub4E2RHwc30\" style=\"display:block; \">🎶\n' );
document.write( '    \n' );
document.write( '    <td>TRUE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    </tr>\n' );
document.write( '    <tr>\n' );
document.write( '    <td>No Future no hope</td>\n' );
document.write( '    <td>Defiance</td>\n' );
document.write( '    <td align=\"right\">1995</td>\n' );
document.write( '    <td>US</td>\n' );
document.write( '    <td><a href=\"https://www.youtube.com/watch?v=zMqWHxUbbhQ\" style=\"display:block; \">🎶\n' );
document.write( '    \n' );
document.write( '    <td>TRUE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    </tr>\n' );
document.write( '    <tr>\n' );
document.write( '    <td>Album "Collection of Pop Classics"</td>\n' );
document.write( '    <td>Reagan youth</td>\n' );
document.write( '    <td align=\"right\">1994</td>\n' );
document.write( '    <td>US</td>\n' );
document.write( '    <td><a href=\"https://www.youtube.com/watch?v=ix9VCgrJY98&t=35s\" style=\"display:block; \">🎶\n' );
document.write( '    \n' );
document.write( '    <td>TRUE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>TRUE</td>\n' );
document.write( '    </tr>\n' );
document.write( '    <tr>\n' );
document.write( '    <td>The Shape of Punk to Come: A Chimerical Bombination in 12 Bursts</td>\n' );
document.write( '    <td>Refused</td>\n' );
document.write( '    <td align=\"right\">1997</td>\n' );
document.write( '    <td>Sweden</td>\n' );
document.write( '    <td><a href=\"https://www.youtube.com/watch?v=SXJRmvQfWjo\" style=\"display:block; \">🎶\n' );
document.write( '    \n' );
document.write( '    <td>TRUE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    </tr>\n' );
document.write( '    <tr>\n' );
document.write( '    <td>Songs to fan the flames of discontent</td>\n' );
document.write( '    <td>Refused</td>\n' );
document.write( '    <td align=\"right\">1996</td>\n' );
document.write( '    <td>Sweden</td>\n' );
document.write( '    <td><a href=\"https://www.youtube.com/watch?v=LhSIwvCORZQ\" style=\"display:block; \">🎶\n' );
document.write( '    \n' );
document.write( '    <td>TRUE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    </tr>\n' );
document.write( '    <tr>\n' );
document.write( '    <td>The Demo compilation</td>\n' );
document.write( '    <td>Refused</td>\n' );
document.write( '    <td align=\"right\">1997</td>\n' );
document.write( '    <td>Sweden</td>\n' );
document.write( '    <td><a href=\"https://www.youtube.com/watch?v=dPNuIgRckDs\" style=\"display:block; \">🎶\n' );
document.write( '    \n' );
document.write( '    <td>TRUE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    </tr>\n' );
document.write( '    <tr>\n' );
document.write( '    <td>The day the country died</td>\n' );
document.write( '    <td>subhumans</td>\n' );
document.write( '    <td align=\"right\">1983</td>\n' );
document.write( '    <td>UK</td>\n' );
document.write( '    <td><a href=\"https://www.youtube.com/watch?v=d7_TPRZDSNg\" style=\"display:block; \">🎶\n' );
document.write( '    \n' );
document.write( '    <td>TRUE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>TRUE</td>\n' );
document.write( '    </tr>\n' );
document.write( '    <tr>\n' );
document.write( '    <td> </td>\n' );
document.write( '    <td> </td>\n' );
document.write( '    <td align=\"right\"></td>\n' );
document.write( '    <td> </td>\n' );
document.write( '    <td> </td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    </tr>\n' );
document.write( '    <tr>\n' );
document.write( '    <td> </td>\n' );
document.write( '    <td> </td>\n' );
document.write( '    <td align=\"right\"></td>\n' );
document.write( '    <td> </td>\n' );
document.write( '    <td> </td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    </tr>\n' );
document.write( '    <tr>\n' );
document.write( '    <td>der achte maerz ist frauentag</td>\n' );
document.write( '    <td>fasia jansen</td>\n' );
document.write( '    <td align=\"right\"></td>\n' );
document.write( '    <td> </td>\n' );
document.write( '    <td>dropbox folder</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    </tr>\n' );
document.write( '    <tr>\n' );
document.write( '    <td>die moorsoldaten</td>\n' );
document.write( '    <td>fasia jansen</td>\n' );
document.write( '    <td align=\"right\"></td>\n' );
document.write( '    <td> </td>\n' );
document.write( '    <td>dropbox folder</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    </tr>\n' );
document.write( '    <tr>\n' );
document.write( '    <td>franzoesisches partisanenlied</td>\n' );
document.write( '    <td>fasia jansen</td>\n' );
document.write( '    <td align=\"right\"></td>\n' );
document.write( '    <td> </td>\n' );
document.write( '    <td>dropbox folder</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    </tr>\n' );
document.write( '    <tr>\n' );
document.write( '    <td>kerkerlied</td>\n' );
document.write( '    <td>fasia jansen</td>\n' );
document.write( '    <td align=\"right\"></td>\n' );
document.write( '    <td> </td>\n' );
document.write( '    <td>dropbox folder</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    </tr>\n' );
document.write( '    <tr>\n' );
document.write( '    <td>lied der italienischen partisanen</td>\n' );
document.write( '    <td>fasia jansen</td>\n' );
document.write( '    <td align=\"right\"></td>\n' );
document.write( '    <td> </td>\n' );
document.write( '    <td>dropbox folder</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    </tr>\n' );
document.write( '    <tr>\n' );
document.write( '    <td>portugiesischer april</td>\n' );
document.write( '    <td>fasia jansen</td>\n' );
document.write( '    <td align=\"right\"></td>\n' );
document.write( '    <td> </td>\n' );
document.write( '    <td>dropbox folder</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    </tr>\n' );
document.write( '    <tr>\n' );
document.write( '    <td>sacco und vanzetti</td>\n' );
document.write( '    <td>fasia jansen</td>\n' );
document.write( '    <td align=\"right\"></td>\n' );
document.write( '    <td> </td>\n' );
document.write( '    <td>dropbox folder</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    </tr>\n' );
document.write( '    <tr>\n' );
document.write( '    <td>strange fruit</td>\n' );
document.write( '    <td>fasia jansen</td>\n' );
document.write( '    <td align=\"right\"></td>\n' );
document.write( '    <td> </td>\n' );
document.write( '    <td>dropbox folder</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    </tr>\n' );
document.write( '    <tr>\n' );
document.write( '    <td>venceremos</td>\n' );
document.write( '    <td>fasia jansen</td>\n' );
document.write( '    <td align=\"right\"></td>\n' );
document.write( '    <td> </td>\n' );
document.write( '    <td>dropbox folder</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    </tr>\n' );
document.write( '    <tr>\n' );
document.write( '    <td>born to die</td>\n' );
document.write( '    <td>MDC</td>\n' );
document.write( '    <td align=\"right\">1982</td>\n' );
document.write( '    <td> </td>\n' );
document.write( '    <td>dropbox folder</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    </tr>\n' );
document.write( '    <tr>\n' );
document.write( '    <td>They're Back Again, Here They Come</td>\n' );
document.write( '    <td>The Cigarettes</td>\n' );
document.write( '    <td align=\"right\">1979</td>\n' );
document.write( '    <td> </td>\n' );
document.write( '    <td>dropbox folder</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    </tr>\n' );
document.write( '    <tr>\n' );
document.write( '    <td>National Front</td>\n' );
document.write( '    <td>The Pigs</td>\n' );
document.write( '    <td align=\"right\">1977</td>\n' );
document.write( '    <td> </td>\n' );
document.write( '    <td>dropbox folder</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    </tr>\n' );
document.write( '    <tr>\n' );
document.write( '    <td>Violence Grows</td>\n' );
document.write( '    <td>Fatal Microbes</td>\n' );
document.write( '    <td align=\"right\"></td>\n' );
document.write( '    <td> </td>\n' );
document.write( '    <td>dropbox folder</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    </tr>\n' );
document.write( '    <tr>\n' );
document.write( '    <td>Antifa Hooligans</td>\n' );
document.write( '    <td>Los Fastidios</td>\n' );
document.write( '    <td align=\"right\"></td>\n' );
document.write( '    <td> </td>\n' );
document.write( '    <td>dropbox folder</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    </tr>\n' );
document.write( '    <tr>\n' );
document.write( '    <td>Peace Dilemma</td>\n' );
document.write( '    <td>Rondos</td>\n' );
document.write( '    <td align=\"right\"></td>\n' );
document.write( '    <td>netherlands?</td>\n' );
document.write( '    <td>dropbox folder</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    </tr>\n' );
document.write( '    <tr>\n' );
document.write( '    <td>Getting Things Done</td>\n' );
document.write( '    <td>The Astronauts</td>\n' );
document.write( '    <td align=\"right\">1979</td>\n' );
document.write( '    <td>UK</td>\n' );
document.write( '    <td>dropbox folder</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    </tr>\n' );
document.write( '    <tr>\n' );
document.write( '    <td>which side will you be on?</td>\n' );
document.write( '    <td>Rondos</td>\n' );
document.write( '    <td align=\"right\"></td>\n' );
document.write( '    <td> </td>\n' );
document.write( '    <td>dropbox folder</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    </tr>\n' );
document.write( '    <tr>\n' );
document.write( '    <td>work together</td>\n' );
document.write( '    <td>The Oppressed</td>\n' );
document.write( '    <td align=\"right\"></td>\n' );
document.write( '    <td> </td>\n' );
document.write( '    <td>dropbox folder</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    </tr>\n' );
document.write( '    <tr>\n' );
document.write( '    <td>Racist Friend</td>\n' );
document.write( '    <td>The Special AKA</td>\n' );
document.write( '    <td align=\"right\"></td>\n' );
document.write( '    <td>UK</td>\n' );
document.write( '    <td>dropbox folder</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    </tr>\n' );
document.write( '    <tr>\n' );
document.write( '    <td>Netural Zone</td>\n' );
document.write( '    <td>Twisted Nerve</td>\n' );
document.write( '    <td align=\"right\"></td>\n' );
document.write( '    <td> </td>\n' );
document.write( '    <td>dropbox folder</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    </tr>\n' );
document.write( '    <tr>\n' );
document.write( '    <td>Bandcamp:  Anti-Facist Tags</td>\n' );
document.write( '    <td>All-Time Best Selling </td>\n' );
document.write( '    <td align=\"right\"></td>\n' );
document.write( '    <td>bandcamp</td>\n' );
document.write( '    <td><a href=\"https://bandcamp.com/tag/anti-fascist\" style=\"display:block; \">🎶\n' );
document.write( '    \n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    </tr>\n' );
document.write( '    <tr>\n' );
document.write( '    <td>Bandcamp: Anti-Facist Tags</td>\n' );
document.write( '    <td>All Releases </td>\n' );
document.write( '    <td align=\"right\"></td>\n' );
document.write( '    <td>bandcamp</td>\n' );
document.write( '    <td><a href=\"https://bandcamp.com/tag/anti-fascist?tab=all_releases\" style=\"display:block; \">🎶\n' );
document.write( '    \n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    </tr>\n' );
document.write( '    <tr>\n' );
document.write( '    <td>Night Rally</td>\n' );
document.write( '    <td>Elvis Costello</td>\n' );
document.write( '    <td align=\"right\"></td>\n' );
document.write( '    <td> </td>\n' );
document.write( '    <td><a href=\"https://www.youtube.com/watch?v=bWZ32XIsZIU\" style=\"display:block; \">🎶\n' );
document.write( '    \n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    </tr>\n' );
document.write( '    <tr>\n' );
document.write( '    <td>Youth Against Facism</td>\n' );
document.write( '    <td>Sonic Youth</td>\n' );
document.write( '    <td align=\"right\">1992</td>\n' );
document.write( '    <td> </td>\n' );
document.write( '    <td><a href=\"https://www.youtube.com/watch?v=eWzIlCJAw-o\" style=\"display:block; \">🎶\n' );
document.write( '    \n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    </tr>\n' );
document.write( '    <tr>\n' );
document.write( '    <td>Big Brother</td>\n' );
document.write( '    <td>Stevie Wonder</td>\n' );
document.write( '    <td align=\"right\">1972</td>\n' );
document.write( '    <td> </td>\n' );
document.write( '    <td><a href=\"https://www.youtube.com/watch?v=qJV-ExBT7DU\" style=\"display:block; \">🎶\n' );
document.write( '    \n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    </tr>\n' );
document.write( '    <tr>\n' );
document.write( '    <td>Take the Power Back</td>\n' );
document.write( '    <td>Rage Against the Machine</td>\n' );
document.write( '    <td align=\"right\"></td>\n' );
document.write( '    <td> </td>\n' );
document.write( '    <td><a href=\"https://www.youtube.com/watch?v=qKSNABST4b0\" style=\"display:block; \">🎶\n' );
document.write( '    \n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    </tr>\n' );
document.write( '    <tr>\n' );
document.write( '    <td>Letter to the Free</td>\n' );
document.write( '    <td>Common</td>\n' );
document.write( '    <td align=\"right\"></td>\n' );
document.write( '    <td> </td>\n' );
document.write( '    <td><a href=\"https://www.youtube.com/watch?v=TRlTnJr_7ec&feature=emb_title\" style=\"display:block; \">🎶\n' );
document.write( '    \n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    </tr>\n' );
document.write( '    <tr>\n' );
document.write( '    <td>Clampdown</td>\n' );
document.write( '    <td>The Clash</td>\n' );
document.write( '    <td align=\"right\"></td>\n' );
document.write( '    <td> </td>\n' );
document.write( '    <td><a href=\"https://www.youtube.com/watch?v=LQ82BX0hGBM&feature=emb_title\" style=\"display:block; \">🎶\n' );
document.write( '    \n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    </tr>\n' );
document.write( '    <tr>\n' );
document.write( '    <td>Only A Pawn in Their Game</td>\n' );
document.write( '    <td>Bob Dylan</td>\n' );
document.write( '    <td align=\"right\">1964</td>\n' );
document.write( '    <td> </td>\n' );
document.write( '    <td><a href=\"https://www.youtube.com/watch?v=KY2lQV3ADfc&feature=emb_title\" style=\"display:block; \">🎶\n' );
document.write( '    \n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    </tr>\n' );
document.write( '    <tr>\n' );
document.write( '    <td>Europe Is Lost</td>\n' );
document.write( '    <td>Kate Tempest</td>\n' );
document.write( '    <td align=\"right\">2015</td>\n' );
document.write( '    <td> </td>\n' );
document.write( '    <td><a href=\"https://www.youtube.com/watch?v=QSVyyykaEOo\" style=\"display:block; \">🎶\n' );
document.write( '    \n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    </tr>\n' );
document.write( '    <tr>\n' );
document.write( '    <td>God Save the Queen</td>\n' );
document.write( '    <td>The Sex Pistols</td>\n' );
document.write( '    <td align=\"right\">1977</td>\n' );
document.write( '    <td> </td>\n' );
document.write( '    <td><a href=\"https://www.youtube.com/watch?v=02D2T3wGCYg&feature=emb_title\" style=\"display:block; \">🎶\n' );
document.write( '    \n' );
document.write( '    \n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    </tr>\n' );
document.write( '    <tr>\n' );
document.write( '    <td>The Revolution Will Not Be Televised</td>\n' );
document.write( '    <td>Gil Scott-Heron</td>\n' );
document.write( '    <td align=\"right\">1970</td>\n' );
document.write( '    <td> </td>\n' );
document.write( '    <td><a href=\"https://www.youtube.com/watch?v=vwSRqaZGsPw&feature=emb_title\" style=\"display:block; \">🎶\n' );
document.write( '    \n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    </tr>\n' );
document.write( '    <tr>\n' );
document.write( '    <td>All You Facists</td>\n' );
document.write( '    <td>Billy Bragg and Wilco</td>\n' );
document.write( '    <td align=\"right\">2000</td>\n' );
document.write( '    <td> </td>\n' );
document.write( '    <td><a href=\"https://www.youtube.com/watch?v=aV4zqixpx4A\" style=\"display:block; \">🎶\n' );
document.write( '    \n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    </tr>\n' );
document.write( '    <tr>\n' );
document.write( '    <td>Fight the Power</td>\n' );
document.write( '    <td>Public Enemy</td>\n' );
document.write( '    <td align=\"right\">1989</td>\n' );
document.write( '    <td> </td>\n' );
document.write( '    <td><a href=\"https://www.youtube.com/watch?v=mmo3HFa2vjg\" style=\"display:block; \">🎶\n' );
document.write( '    \n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    </tr>\n' );
document.write( '    <tr>\n' );
document.write( '    <td>All You Fascists Bound To Lose</td>\n' );
document.write( '    <td>Resistance Revival Chorus</td>\n' );
document.write( '    <td align=\"right\">2020</td>\n' );
document.write( '    <td>USA</td>\n' );
document.write( '    <td><a href=\"https://www.youtube.com/watch?v=dWUa7aAIfLE\" style=\"display:block; \">🎶\n' );
document.write( '    \n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    </tr>\n' );
document.write( '    <tr>\n' );
document.write( '    <td>Tear the Facists Down</td>\n' );
document.write( '    <td>Woody Guthrie</td>\n' );
document.write( '    <td align=\"right\"></td>\n' );
document.write( '    <td> </td>\n' );
document.write( '    <td><a href=\"https://www.youtube.com/watch?v=jKVnur5DkdI\" style=\"display:block; \">🎶\n' );
document.write( '    \n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    </tr>\n' );
document.write( '    <tr>\n' );
document.write( '    <td>International News</td>\n' );
document.write( '    <td>National Wake</td>\n' );
document.write( '    <td align=\"right\">1977</td>\n' );
document.write( '    <td>Johannisburg, South Africa</td>\n' );
document.write( '    <td><a href=\"https://www.youtube.com/watch?v=ze5yn6KneJg&feature=emb_title\" style=\"display:block; \">🎶\n' );
document.write( '    \n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    </tr>\n' );
document.write( '    <tr>\n' );
document.write( '    <td>Abortus Vrij de Vrouw Beslist</td>\n' );
document.write( '    <td>Basta</td>\n' );
document.write( '    <td align=\"right\">1977</td>\n' );
document.write( '    <td>Belgium</td>\n' );
document.write( '    <td><a href=\"https://www.youtube.com/watch?v=F3s-BeYB3bY\" style=\"display:block; \">🎶\n' );
document.write( '    \n' );
document.write( '    \n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    </tr>\n' );
document.write( '    <tr>\n' );
document.write( '    <td>The Dicks Hate the Police</td>\n' );
document.write( '    <td>The Dicks</td>\n' );
document.write( '    <td align=\"right\">1980</td>\n' );
document.write( '    <td>Austin, Texas</td>\n' );
document.write( '    <td><a href=\"https://www.youtube.com/watch?v=09lox_vnJ9Y\" style=\"display:block; \">🎶\n' );
document.write( '    \n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    </tr>\n' );
document.write( '    <tr>\n' );
document.write( '    <td>Bully Boys</td>\n' );
document.write( '    <td>Poison Girls</td>\n' );
document.write( '    <td align=\"right\">1980</td>\n' );
document.write( '    <td>Essex, England</td>\n' );
document.write( '    <td><a href=\"https://www.youtube.com/watch?v=1VeZ10yyTj8\" style=\"display:block; \">🎶\n' );
document.write( '    \n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    </tr>\n' );
document.write( '    <tr>\n' );
document.write( '    <td>Nazis Wieder in Ostberlin</td>\n' );
document.write( '    <td>Namenlos</td>\n' );
document.write( '    <td align=\"right\">1983</td>\n' );
document.write( '    <td>East Berlin</td>\n' );
document.write( '    <td><a href=\"https://www.youtube.com/watch?v=oe6lkVLoUhk\" style=\"display:block; \">🎶\n' );
document.write( '    \n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    </tr>\n' );
document.write( '    <tr>\n' );
document.write( '    <td>Political Song for Michael Jackson to Sing</td>\n' );
document.write( '    <td>Minutemen</td>\n' );
document.write( '    <td align=\"right\">1984</td>\n' );
document.write( '    <td>San Pedro, California</td>\n' );
document.write( '    <td><a href=\"https://www.youtube.com/watch?v=KxjEi4tgvU0\" style=\"display:block; \">🎶\n' );
document.write( '    \n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    </tr>\n' );
document.write( '    <tr>\n' );
document.write( '    <td>La Música del General/Esto Es Pinochet Boys</td>\n' );
document.write( '    <td>Los Pinochet Boys</td>\n' );
document.write( '    <td align=\"right\">1984</td>\n' );
document.write( '    <td>Santiago, Chile</td>\n' );
document.write( '    <td><a href=\"https://www.youtube.com/watch?v=ZDxvh2G0iNc\" style=\"display:block; \">🎶\n' );
document.write( '    \n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    </tr>\n' );
document.write( '    <tr>\n' );
document.write( '    <td>Sistema Podrido</td>\n' );
document.write( '    <td>Massacre 68</td>\n' );
document.write( '    <td align=\"right\">1990</td>\n' );
document.write( '    <td>Mexico City</td>\n' );
document.write( '    <td><a href=\"https://www.youtube.com/watch?v=sJf0pYFreYw\" style=\"display:block; \">🎶\n' );
document.write( '    \n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    </tr>\n' );
document.write( '    <tr>\n' );
document.write( '    <td>Cruel and Unusual Punishment (full album)</td>\n' );
document.write( '    <td>Whitephosphorous</td>\n' );
document.write( '    <td align=\"right\">2020</td>\n' );
document.write( '    <td>USA</td>\n' );
document.write( '    <td><a href=\"https://trepanationrecordings.bandcamp.com/album/cruel-and-unusual-punishment\" style=\"display:block; \">🎶\n' );
document.write( '    \n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    <td>FALSE</td>\n' );
document.write( '    </tr>\n' );
document.write( '    </tbody></table>\n' );
document.write( '    </tbody></table>\n' );
document.write( '    </tbody></table>\n' );
document.write( '  </body>\n' );
document.write( '</html>' );
